-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT from online_sale
where DATE_FORMAT(SALES_DATE, '%Y%m') = '202203'
union
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT from offline_sale 
where DATE_FORMAT(SALES_DATE, '%Y%m') = '202203'
order by SALES_DATE, PRODUCT_ID, USER_ID